kitchen_restaurant_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu.urls", namespace="menu")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menu/urls.py
from django.urls import path
from .views import (
    index,
    about,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    UserCreateView
)


urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("cooks/", CookListView.as_view(), name="cooks-list"),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("user/create/", UserCreateView.as_view(), name="user-create")
]

app_name = "menu"

menu/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class DishType(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True
    )

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Cook(models.Model):
    photo = models.ImageField(upload_to="kitchen-service")
    full_name = models.CharField(max_length=255)
    biography = models.TextField()
    years_of_experience = models.IntegerField()

    class Meta:
        ordering = ("full_name",)

    def __str__(self):
        return f"{self.full_name} {self.biography} {self.years_of_experience}"


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=4, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")
    image = models.ImageField(upload_to="kitchen-service")

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "dishes"

    def __str__(self):
        return f"{self.name} {self.description} {self.price}"


class User(AbstractUser):
    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

menu/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from menu.models import User


class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish name"
            }
        )

    )

menu/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.shortcuts import render, HttpResponse
from django.views import generic

from .models import Dish, DishType, Cook, User
from .forms import DishSearchForm, UserCreateForm


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "menu/index.html")


def about(request: HttpRequest) -> HttpResponse:
    num_dish = Dish.objects.count()
    num_dish_type = DishType.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dish": num_dish,
        "num_dish_type": num_dish_type,
        "num_cooks": num_cooks
    }

    return render(request, "menu/about.html", context=context)


class DishListView(LoginRequiredMixin, generic.ListView):
    paginate_by = 5
    context_object_name = "dish_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.all().select_related("dish_type")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    queryset = Dish.objects.select_related("dish_type")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes")


class UserCreateView(generic.CreateView):
    model = User
    form_class = UserCreateForm
    success_url = reverse_lazy("menu:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">

    <title>Klassy Cafe - Restaurant HTML Template</title>
    
    <!-- Additional CSS Files -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/templatemo-klassy-cafe.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">

    </head>
    
    <body>
    
    <!-- ***** Header Area Start ***** -->
    
    {% block header %}
      {% include "includes/header.html" %}
    {% endblock %}
    
    <!-- ***** Header Area End ***** -->
    
        {% block content %}
        {% endblock %}
    
    <!-- ***** Footer Start ***** -->

    {% block footer %}
      {% include "includes/footer.html" %}
    {% endblock %}
    <!-- jQuery -->
    <script src="{% static 'assets/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'assets/js/popper.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <!-- Plugins -->
    <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>
    <script src="{% static 'assets/js/datepicker.js' %}"></script>
    <script src="{% static 'assets/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets/js/imgfix.min.js' %}"></script>
    <script src="{% static '/assets/js/slick.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <!-- Global Init -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script>

      $(function() {
          var selectedClass = "";
          $("p").click(function(){
          selectedClass = $(this).attr("data-rel");
          $("#portfolio").fadeTo(50, 0.1);
              $("#portfolio div").not("."+selectedClass).fadeOut();
          setTimeout(function() {
            $("."+selectedClass).fadeIn();
            $("#portfolio").fadeTo(50, 1);
          }, 500);
                
          });
      });

    </script>
  </body>
</html>

templates/includes/footer.html
{% load static %}
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-xs-12">
        <div class="right-text-content">
          <ul class="social-icons">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="logo">
          <a href="index.html"><img src="{% static "assets/images/white-logo.png" %}" alt=""></a>
        </div>
      </div>
      <div class="col-lg-4 col-xs-12">
        <div class="left-text-content">
          <p>© Copyright Klassy Cafe Co.

            <br>Design: TemplateMo</p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/header.html
<header class="header-area header-sticky">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="main-nav">
          <!-- ***** Logo Start ***** -->
          <a href="{% url 'menu:index' %}" class="logo">
            {% load static %}
            <img src="{% static 'assets/images/klassy-logo.png' %}" align="klassy cafe html template" alt="logo">
          </a>
          <!-- ***** Logo End ***** -->
          <!-- ***** Menu Start ***** -->
          <ul class="nav">
            <li><a href="{% url 'menu:index' %}">Home</a></li>
            <li><a href="{% url 'menu:about' %}">About</a></li>
            <li><a href="{% url 'menu:dish-list' %}">Menu</a></li>
            <li><a href="{% url 'menu:cooks-list' %}">Chefs</a></li>
            {% if user.is_authenticated %}
              <li>
                <a href="">
                  <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="logout-button">Log out</button>
                  </form>
                </a>
              </li>
              <li> User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
            {% else %}
              <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
            {% endif %}
          </ul>
          <a class='menu-trigger'>
            <span>Menu</span>
          </a>
          <!-- ***** Menu End ***** -->
        </nav>
      </div>
    </div>
  </div>
</header>

templates/menu/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section class="section" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-xs-12">
          <div class="left-text-content">
            <div class="section-heading">
              <h6>About Us</h6>
              <h2>We Leave A Delicious Memory For You</h2>
            </div>
            <p>
              {{ num_cooks }} our <a href="{% url "menu:cooks-list" %}">chefs</a> work for you every day.
            </p>
            <p>
              They are ready to cook {{ num_dish_type }} types of dishes from all over the world.
            </p>
            <p>
              In total, {{ num_cooks }} different <a href="{% url "menu:dish-list" %}">dishes</a> are prepared in our restaurant, which you can enjoy at a time convenient for you.
            </p>
            <div class="row">
              <div class="col-4">
                <img src={% static "assets/images/about-thumb-01.jpg" %} alt="">
              </div>
              <div class="col-4">
                <img src="{% static "assets/images/about-thumb-02.jpg" %}" alt="">
              </div>
              <div class="col-4">
                <img src="{% static "assets/images/about-thumb-03.jpg" %}" alt="">
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-xs-12">
          <div class="right-content">
            <div class="thumb">
              <a rel="nofollow" href="http://youtube.com"><i class="fa fa-play"></i></a>
              <img src="{% static "assets/images/about-video-bg.jpg" %}" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/menu/cook_detail.html
{% extends "base.html" %}
{% block content %}

  <section class="section" id="cookDetail">
    <div class="container">
      <div class="cookTitle section-heading">
        <h1>{{ object.full_name }}</h1>
      </div>
      <div class="cookPhoto">
        <img src="{{ object.photo.url }}" alt="{{ object.full_name }}" style="width: 100%;">
      </div>
      <div class="row">
        <div class="col-lg">
          <div class="cookDetails">
           <p>{{ object.biography }}</p>
            <h3>Experience: {{ object.years_of_experience }} years</h3>
          </div>
        </div>
        <div class="col-lg">
          <h3><strong>Dishes:</strong></h3><br>
            {% for dish in object.dishes.all %}
              <a href="{% url 'menu:dish-detail' dish.pk %}" style="text-decoration: none;"><h5>{{ dish.name }}</h5></a><br>
            {% endfor %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/menu/cook_list.html
{% extends "base.html" %}
{% block content %}
  {% load static %}
  <section class="section" id="chefs">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 offset-lg-4 text-center">
          <div class="section-heading">
            <h6>Our Chefs</h6>
            <h2>We offer the best ingredients for you</h2>
          </div>
        </div>
      </div>
      {% if cook_list %}
        {% for cook in cook_list %}
          <div class="row">
            <div class="col-lg-4">
              <div class="chef-item">
                <div class="thumb">
                  <div class="overlay"></div>
                    <ul class="social-icons">
                      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                  <img src="{{ cook.photo.url }}" alt="chef">
                </div>
                <div class="down-content">
                  <a href="{% url 'menu:cook-detail' cook.pk %}"><h4>{{ cook.full_name }}</h4></a>
                  <span>{{ cook.years_of_experience }} years of experience</span>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </section>
{% endblock %}

templates/menu/dish_detail.html
{% extends "base.html" %}
{% block content %}
 <section class="section" id="dishDetail">
  <div class="container">
    <div class="dishTitle section-heading">
      <h2>{{ dish.name }}</h2>
    </div>
    <br>
    <div class="row">
      <div class="col-lg">
        <div class="dishImage">
          <img src="{{ dish.image.url }}" alt="{{ dish.name }}" style="width: 100%">
          <div class="middleText">
            <button class="btn btn-outline-success">Order</button>
          </div>
        </div>
      </div>
      <div class="col-lg">
        <div class="dishDescription">
          {{ dish.description }}
        </div>
        <br>
        <div class="dishPrice row space-between">
          <div class="col-sm">
            <h3>Price: {{ dish.price }} $</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
 </section>
  
{% endblock %}

templates/menu/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <section class="section" id="menu">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="section-heading">
            <br>
            <h6>Our Menu</h6>
            <h2>Our selection of dish with quality taste</h2>

            <form action="" method="get" class="form-inline search-form">
              {{ search_form|crispy }}
              <input type="submit" class="btn btn-primary" value="Search">
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="menu-item-carousel">
      <div class="col-lg-12">
        <div class="owl-menu-item owl-carousel">
          {% if dish_list %}
            {% for dish in dish_list %}
              <a href="{% url 'menu:dish-detail' dish.pk %}">
                <div class="item">
                  <div class='card card1' style="background-image: url( '{{ dish.image.url }}' )">
                    <div class="price"><h6>${{ dish.price }}</h6></div>
                    <div class='info'>
                      <h1 class='title'>{{ dish.name }}</h1>
                      <p class='description'>{{ dish.description }}</p>
                    </div>
                  </div>
                </div>
              </a>
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/menu/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-4">
        <div class="left-content">
          <div class="inner-content">
            <h4>KlassyCafe</h4>
            <h6>THE BEST EXPERIENCE</h6>
            <div class="main-white-button scroll-to-section">
              <a href="{% url 'menu:user-create' %}">Create account</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="main-banner header-text">
          <div class="Modern-Slider">
            <div class="item">
              <div class="img-fill">
                <img src="{% static 'assets/images/slide-01.jpg' %}" alt="banner">
              </div>
            </div>
            <div class="item">
              <div class="img-fill">
                <img src="{% static 'assets/images/slide-02.jpg' %}" alt="banner">
              </div>
            </div>
            <div class="item">
              <div class="img-fill">
                <img src="{% static 'assets/images/slide-03.jpg' %}" alt="banner">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/menu/user_form.html
{% extends "base.html" %}

{% block content %}

<section class="section" id="createUser">
  <div class="container">
    <div class="row">
      <div class="col-lg">
        <h1>Create User</h1>
        <form action="" method="post" novalidate>
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}